a = []
a1 = input("enter 1st fruit name : ")
a.append(a1)
a2 = input("enter 2st fruit name : ")
a.append(a2)
a3 = input("enter 3st fruit name : ")
a.append(a3)
a4= input("enter 4st fruit name : ")
a.append(a4)
a5 = input("enter 5st fruit name : ")
a.append(a5)
a6 = input("enter 6st fruit name : ")
a.append(a6)
print(a)